Cycle through headings on Ctrl+H
StackExchange/Stacks-Editor pull request #110
Opened 2022-04-11 12:27 UTC by double-beep

- Toggle code blocks and headings when <kbd>Ctrl</kbd> + <kbd>M</kbd> and <kbd>Ctrl</kbd> + <kbd>H</kbd> are pressed respectively.
- Cycle through headings on <kbd>Ctrl</kbd> + <kbd>H</kbd>.

Closes #45, #105

2022-04-11 21:00 UTC, b-kelly requested changes
Thank you for the PR! I'll give this a lookover soon, but in the meanwhile, could you add some unit tests in as well? I believe we have some existing command unit tests you could use as inspiration. If not, I can add a few for you to base yours off of.

2022-04-12 04:22 UTC, double-beep commented
@b-kelly I have already added an e2e test for Ctrl + H - do I need to add more tests?

2022-05-02 16:05 UTC, b-kelly requested changes
Left a few comments on the approach. I'd also like to add this functionality to markdown mode as well.

Regarding unit vs e2e tests - we'd like to prefer unit tests whenever possible, especially for functionality that doesn't need a view to run (as is the case here with the state commands). Unit tests are much faster and can be made much more complex / complete.

2022-05-02 16:05 UTC, b-kelly commented on src/rich-text/commands/index.ts
> +export function cycleThroughHeadings(nodeType: NodeType) {
nit: Add `/** */` docs to all new + exported functions

2022-05-02 16:05 UTC, b-kelly commented on src/rich-text/commands/index.ts
> +        const delay = Date.now() - headingInfo.time;
I'd prefer to not check for delays in our underlying code. I think this is to support successive presses causing cycling, but single presses causing toggle? If that's something we'd like to pursue, let's move that logic into the keybind file instead

2022-05-21 06:49 UTC, closed without merging