fix: only select current node on triple click
StackExchange/Stacks-Editor pull request #128
Opened 2022-05-18 21:14 UTC by dancormier

fixes #27

Note: this solution was largely lifted from [a comment on the ProseMirror discussion forum](https://discuss.prosemirror.net/t/how-can-i-let-the-browser-instead-of-prosemirror-view-handle-triple-clicks/4526/3).

<details>
<summary>Before</summary>

![20220518-051204](https://user-images.githubusercontent.com/647177/169156777-e13b71bc-5252-46e6-b00d-7639b52158e7.gif)

</details>

<details>
<summary>After</summary>

![20220518-051137](https://user-images.githubusercontent.com/647177/169156795-911c4c73-4a27-49b6-9a5d-b7841d3588d6.gif)

</details>

2022-06-02 19:09 UTC, b-kelly requested changes
As mentioned on #109:
> I don't think this is a proper fix to the root issue, but rather fixing one of the symptoms. I've tackled the root cause here a few times, but have yet to implement a proper fix

That being said, the fix for this issue is pretty elusive, so this may work in the meanwhile. I'd _really_ like some tests for this. I agree that unit tests may not be feasible, but we can at least get some e2e tests in.

2022-06-02 19:09 UTC, b-kelly commented on src/commonmark/plugins/triple-click-handler.ts
> +/** Plugin that selects only the current node on triple click */
The doc here is slightly misleading:

```suggestion
/** Plugin that restores browser default triple-click handling behavior */
```

2022-06-14 19:39 UTC, dancormier commented
> …I'd _really_ like some tests for this. I agree that unit tests may not be feasible, but we can at least get some e2e tests in.

You got it. I added [E2E tests for triple click and double click](https://github.com/StackExchange/Stacks-Editor/pull/128/commits/9a5e9a697fb415be742161ff1e365533a01e6e6d) for good measure.

2022-06-29 12:47 UTC, b-kelly commented
Getting failing tests locally:

```
  1) [chromium] › commonmark\editor.e2e.test.ts:33:5 › markdown mode › should select word on double click

    Timeout of 30000ms exceeded.

    Error: expect(received).toEqual(expected) // deep equality

    Expected: "paragraph"
    Received: "paragraph "

      38 |             window.getSelection().toString()
      39 |         );
    > 40 |         expect(selectedText).toEqual("paragraph");
         |                              ^
      41 |     });
      42 |
      43 |     test("should select line on triple click", async () => {

        at C:\code\Stacks-Editor\test\commonmark\editor.e2e.test.ts:40:30
```
```
  3 failed
    [chromium] › commonmark\editor.e2e.test.ts:33:5 › markdown mode › should select word on double click
    [firefox] › commonmark\editor.e2e.test.ts:33:5 › markdown mode › should select word on double click
    [webkit] › commonmark\editor.e2e.test.ts:33:5 › markdown mode › should select word on double click
```

2022-06-29 15:04 UTC, dancormier commented
@b-kelly That's very odd! Is there a chance that triple click operates differently on Windows than Mac OS?

I'm having some weird E2E test issues locally, but if I run the commonmark tests directly, all they pass 🤷‍♂️

```
npx playwright test test/commonmark/editor.e2e.test.ts 

Running 5 tests using 1 worker

  ✓  test/commonmark/editor.e2e.test.ts:23:5 › markdown mode › should show toggle switch (2s)
  ✓  test/commonmark/editor.e2e.test.ts:29:5 › markdown mode › should render menu bar (18ms)
  ✓  test/commonmark/editor.e2e.test.ts:33:5 › markdown mode › should select word on double click (129ms)
  ✓  test/commonmark/editor.e2e.test.ts:43:5 › markdown mode › should select line on triple click (142ms)
  ✓  test/commonmark/editor.e2e.test.ts:56:5 › markdown mode › should not highlight bold menu button after click (114ms)


  5 passed (3s)
```

2022-06-30 20:11 UTC, merged