fix(commonmark-editor) Update preview timing and styles
StackExchange/Stacks-Editor pull request #160
Opened 2022-07-11 14:32 UTC by yellis

- Shorter delay on preview rendering (100 ms instead of 1 second), to make the experience more responsive, closer to how it is on the site today
- Turn on html for renderer. We use markdown-it on the main site for the current preview renderer, and html is enabled there without issue. When it is on, it is going through our sanitize already. So unless anything else missing, no reason not to have it on
- Customize open and close table in markdown-it the [same way that we do it](https://github.com/StackEng/StackOverflow/blob/baba2a3a08bd75da2616315662d7198f0c50b856/StackOverflow/_Scripts/LegacyJS/markdown/markdown-it-loader.js#L10-L10) on the current preview renderer.

2022-07-11 19:21 UTC, yellis commented
/cc @b-kelly

2022-07-11 19:26 UTC, dancormier approved these changes
👍 Thanks for the PR and the clear PR description.

2022-07-11 19:26 UTC, dancormier commented on src/commonmark/plugins/preview.ts
> +const DEFAULT_RENDER_DELAY_MS = 100;
Seems reasonable to me. The 1000ms delay is probably a bit too conservative.

2022-07-11 19:59 UTC, b-kelly requested changes

2022-07-11 19:59 UTC, b-kelly commented on src/commonmark/plugins/preview.ts
> +                html: true,
We _cannot_ turn this on until the TODO comment (that was deleted here) is addressed. This is a major security vulnerability (self XSS) that I'm not willing to ship. If consumers want to override it, they can.

2022-07-11 19:59 UTC, b-kelly commented on src/shared/markdown-parser.ts
> +    else {
I'd really rather not start sticking random render rules into this file. My vote is to either pull in the Stack Overflow renderer wholesale or not at all. As it stands, the renderer used currently is unmodified, so it doesn't support things like taglinks or spoilers either.

2022-07-11 20:27 UTC, yellis commented on src/shared/markdown-parser.ts
> +    else {
What would "pulling in the renderer wholesale" entail? We are going to be looking to have parity between this preview and the existing one anyway.

2022-07-12 15:03 UTC, b-kelly commented on src/shared/markdown-parser.ts
> +    else {
Yes, that's how the preview is designed currently. See the commonmark preview settings [here](https://github.com/StackExchange/Stacks-Editor/blob/main/src/commonmark/editor.ts#L46-L52) for more details.

2022-07-20 18:09 UTC, b-kelly commented
Closing PR, as we're abandoning these changes

2022-07-20 18:09 UTC, closed without merging