feat: allow passthrough of accepted image file types to display in image upload UI
StackExchange/Stacks-Editor pull request #304
Opened 2024-04-12 16:17 UTC by kristinalustig

As discussed, this PR introduces a method by which users can pass through a list of strings representing different allowed media types. It then constructs an appropriate string listing out those media types and puts them into the image uploader dialog. Note that I am not sure what types of tests would be appropriate for this sort of change, if any, so if you think this change is large enough to require one, please let me know and I will update.

**PR Checklist**

- [ ] All new/changed functionality includes unit and (optionally) e2e tests as appropriate
- [ ] All new/changed functions have `/** ... */` docs
- [ ] I've added the `bug`/`enhancement` and other labels as appropriate

**Additional context**

For reference, this pairs with SO codebase changes PR # 19347 though each of them should be able to be released independently with no issues.

2024-04-12 22:59 UTC, dancormier requested changes
Thanks for taking this on @kristinalustig!

We currently have a disconnect between the input and validation. Currently, we set the `accept` attribute on the input to `image/*` (so, **any** [image type](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types)). When the user tries to upload something else, we show a validation message  with `jpeg, png, gif` hardcoded:

![image](https://github.com/StackExchange/Stacks-Editor/assets/647177/30910765-a6f0-489c-8407-21f710cd5ba3)

In this PR, we don't address that but we are adding a field to pass file types. Right now, this is only used to generate caption text in the UI, but I think it can be used to populate the `accept` attribute on the input and ensure the validation message lines up with the file types we're accepting.

I've created https://github.com/StackExchange/Stacks-Editor/pull/305 targeting this PR as a proposal for a slightly different approach to what's in this PR. I _think_ it matches the mocks/requirements and just needs a test or two added to `image-upload.test.ts`. Check it out when you get a chance and we'll see if this is a worthwhile approach. I'm happy to chat or pair with you on Monday to go over any details if you'd like.

2024-04-18 22:23 UTC, dancormier reviewed
I made some updates to how we handle the acceptedFileTypes option and how the they're displayed when rendered as text. I think this is in a good place to get merged.

Since I had a hand in much of these changes, I'd like to have @giamir give this a quick look just to make sure that I didn't do anything too funky and that the tests are sufficient.

2024-04-19 08:18 UTC, giamir requested changes
Overall looks good. Great job. 👏 

I left a couple of small requests. One is challenging the product/design requirements to add an `or` (which is currently hardcoded). @kristinalustig you can explain to your designer, PM that the juice is likely not worth the squeeze for that `or`. Let us know if you need support in that conversation. 🙂

Tests are probably good enough I would say Dan. 👍

2024-04-19 08:18 UTC, giamir commented on src/shared/prosemirror-plugins/image-upload.ts
> +                    return i === types.length - 1
I personally find nested ternary operators far more difficult to read than nested ifs. I would probably just write `if`s in here even if it's a bit more verbose.

2024-04-19 08:18 UTC, giamir commented on src/shared/prosemirror-plugins/image-upload.ts
> +        if (types?.length === 0) {
Can types ever be undefined? Doesn't look like it from the function signature.

2024-04-19 08:18 UTC, giamir commented on src/shared/prosemirror-plugins/image-upload.ts
> +                          ? `${type}, or`
I wonder if we need this extra complication here. I would personally challenge the requirement and ask design if we can drop the or here and just use commas as separators. On top of that `or` is not the same in every language and should not be hardcoded.

2024-04-19 08:18 UTC, giamir commented on src/shared/prosemirror-plugins/image-upload.ts
> +                          ? `${type}, or`
Maybe @kristinalustig can double check for us

2024-04-19 20:51 UTC, dancormier approved these changes
@kristinalustig I removed the `getAcceptedFileTypesString` function since it was no only joining strings and removing `image/` in two spots. All tests pass and this looks good to me 🎉

2024-04-22 12:24 UTC, giamir approved these changes

2024-04-22 12:26 UTC, giamir commented
@kristinalustig we can merge this, do you want us to cut a new editor release with the changes straight away? @dancormier or I can do that instead of waiting till next week's "regular" release cycle. Let us know. 

Thank you for contributing to the editor codebase. 🎉

2024-04-23 15:04 UTC, kristinalustig commented
@giamir Ideally we can get it out sooner rather than later, but if that is a huge hassle it should be okay to wait until next week.

2024-04-23 17:33 UTC, giamir commented
> @giamir Ideally we can get it out sooner rather than later, but if that is a huge hassle it should be okay to wait until next week.

No, either @dancormier or myself will cut a release today or tomorrow. No reason to wait.

2024-04-24 08:31 UTC, merged