feat(options): add option for default validate link to use markdown-it validate link
StackExchange/Stacks-Editor pull request #91
Opened 2021-11-01 21:10 UTC by bharney0

Added property to `StacksEditorOptions.parserFeatures` option for allowing users to use the default validate link function from Markdown-It to be used instead of the Stack Overflow's validate link method.

- The default Markdown-It option supports data:image along with a few other link types
![image](https://user-images.githubusercontent.com/51799435/138935938-e46ac117-99b1-49d6-9309-d3795effd229.png)
- Stack Overflow's validate link function only supports http links.
![image](https://user-images.githubusercontent.com/51799435/138936023-b0ad4e21-b1be-447f-8940-032160b1aa80.png)

While implementing image uploading functionality for our own project, the usage of data:image URLs are not supported by the Stack Overflow validateLink.

2021-11-03 15:40 UTC, b-kelly requested changes
Thank you for the feature PR! I'm not opposed to this feature, but I have a few requests before we can merge it.

1. Can you add new tests for this new functionality?
2. `validateLink` is used in a number of places. The change here only checks for validity in the commonmark > rich text conversion. In order to ensure editor-wide validity, we'd also need update the logic in:
   * `inputrules.ts` (translates typed markdown to nodes in rich-text mode)
   * `link-paste-handler.ts` (detects links pasted in rich-text mode and "linkifys" them)
   * `link-tooltop.ts` (used when creating/editing links in rich-text mode)
3. Something to consider would be allowing a user to pass in their own custom validation function. This isn't necessary for merge, but would allow us to plan ahead on the API and not introduce breaking changes later in the project's lifetime.

2021-11-09 16:49 UTC, bharney0 commented
@b-kelly I added the option to the different areas that are impacted by validateLink

 - `inputrules.ts` added check if option.validateLink exists, then use that instead
 - `link-paste-handler.ts` similar logic to use the option.validateLink if it has been passed in
 - `link-tooltip.ts` now using option if available.

I also added unit tests, but in my opinion they are pretty weak and just test the functionality that my own custom validateLink function returns the result I expected. Let me know what you think.

2021-11-09 18:07 UTC, b-kelly commented
@bharney0 Thank you for the changes! I'll take a look at updates this week, likely today or tomorrow.

2022-01-11 17:45 UTC, lamebrain commented
@b-kelly Hi Ben! Have you had a chance to review this yet?

2022-01-18 21:57 UTC, b-kelly commented
I've decided to go a slightly different direction with this. Implemented in 124762a6. Just need to pass a custom `parserFeatures.validateLink` option.

2022-01-18 21:57 UTC, closed without merging